#include <iostream>

const std::string possible_services_RUS[] = {
    "предоставление кредитов",
    "предоставление автокредитов",
    "предоставление ипотечных кредитов",
    "выпуск кредитных карт",
    "выпуск платежных карт",
    "размещение денег на депозитных счетах",
    "размещение денег на текущих счетах",
    "проведение расчетно-кассовых операций",
};

const std::string possible_services[]{
    "providing loans",
    "providing car loans",
    "provision of mortgage loans",
    "issuance of credit cards",
    "issue of payment cards",
    "placement of money in deposit accounts",
    "placement of money on current accounts",
    "carrying out settlement and cash transactions",
};

const std::string possible_bank_names_RUS[] = {
    "Юнайтед Банкорп",
    "Аллайд Файненшл Холдингс",
    "Одна Нация Холдингс Инк.",
    "Бун Банк Групп",
    "Новые национальные банки",
    "Бастион Финанс Корпорейшн",
    "Маршалл Бэнкшарз",
    "Калибр Банк",
    "Уважение к доверию",
    "Голдлиф Банк Корпорейшн",
    "Скай Хай Траст Корпорейшн",
    "Доверительные банки",
    "Гранд Мутьюэл Файненшл Инк.",
    "Гранд Саммит Финансовые Услуги",
    "Пиннакл Банк Систем",
    "Отечественные банки",
    "Полестар Финанс Инк.",
    "Банковая система Лазурный",
    "Ассансанс Банк Корпорейшн",
    "Синдикат банков",
    "Нью Коннекшн Траст Корпорейшн",
    "Уан Кэпитал Банкшерз",
    "Траст Финансовые Услуги",
    "Беттер Лайф Холдингс Инк.",
    "Юнайтед Траст Корп.",
    "Большое Сердце Холдинг",
    "Сурф Финанс",
    "Оружейный кредитный союз",
    "Эгид Бэнкс",
    "Принцип Финанс Инк.",
    "Голдлиф Банк Корпорейшн",
    "Финансовая группа Процветание",
    "Новая национальная холдинговая компания",
    "Кредитный союз Голдлиф",
    "Эдж Траст",
    "Апогей Банк Корпорейшн",
    "Релианс Финансовые Услуги",
    "Фундамент Финансовые Услуги",
    "Альфа Траст",
    "Булварк Финанс Инк.",
    "Омега Банкорп",
    "Калибр Бэнкс Инк.",
    "Селестиал Бэнкс Инкорпорейтед",
    "Мидленд Банк Групп",
    "Фаундворк Банк Групп",
    "Глобал Сетевой Банк Корпорейшн",
    "Финансовая резолюция",
    "Нью Коннекшн Финанс Инк.",
    "Банк Зеленая Долина",
    "Джонс Банкорп",
    "Чудо Финанс",
    "Апекс Корпорейшн",
    "Окулус Траст Корпорейшн",
    "Окулус Файненшл Холдингс",
    "Утешение Траст",
    "Финансовая группа Монолит",
    "Корпорация Монолит",
    "Грейд Холдингс Инк.",
    "Финансовая группа Процветание",
    "Болт Финанс Корпорейшн",
    "Банки Источника",
    "Премиум Банки Инк.",
    "Ситизен Юнион Траст Корпорейшн",
    "Стейт Банк Инк.",
    "Содружество финансовых",
    "Банк Новая волна",
    "Апекс Банк Инк.",
    "Золотой Кредит Траст",
    "Оружейный кредитный союз",
    "Армеймент Банкорп",
    "Бастион Бэнкс Инк.",
    "Голд Альянс Траст Корпорейшн",
    "Просперити Бэнкс Инкорпорейтед",
    "Лайфспарк Банк",
    "Селестиал Холдингс Инк.",
    "Корпорация Земляных работ",
    "Прайм Финанс Корп.",
    "Крест Банк Систем",
    "Киндред Банк Инк.",
    "Принципиальная трастовая корпорация",
    "Дилижанс Банк Система",
    "Кловер Банк Инк.",
    "Победа Бэнкшерз",
    "Национальный финансовый холдинг",
    "Бун Банк Групп",
    "Бун Бэнкс",
    "Проминенс Бэнкс Инк.",
    "Одна Нация Холдингс Инк.",
    "Нью Хайтс Холдингс Инк.",
    "Вирту Финанс Инк.",
    "Корпорация Монолит",
    "Сион Бэнкс Инк.",
    "Калибр Банк Систем",
    "Рост Банк",
    "Ведлок Холдингс",
    "Креденс Бэнкс",
    "Беттер Лайф Бэнкс Инк.",
    "Апекс Файненшл Холдингс",
    "Фундамент Корпорейшн",
    "Калибр Банк Инк.",
};

const std::string possible_bank_names[] = {
    "United Bancorp",
    "Allied Financial Holdings",
    "One Nation Holdings Inc.",
    "Boon Bank Group",
    "New National Banks",
    "Bastion Financial Corp.",
    "Marshall Bancshares",
    "Caliber Bank",
    "Esteem Trust",
    "Goldleaf Bank Corp.",
    "Sky High Trust Corp.",
    "Trust Banks",
    "Grand Mutuel Financial Inc.",
    "Grand Summit Financial Services",
    "Pinnacle Bank System",
    "Domestic Banks",
    "Polestar Financial Inc.",
    "Azure Bank System",
    "Assurance Bank Corp.",
    "Syndicate Banks",
    "New Connection Trust Corp.",
    "One Capital Bancshares",
    "Trust Financial Services",
    "Better Life Holdings Inc.",
    "United Trust Corp.",
    "Big Heart Holdings",
    "Surge Financial",
    "Armament Credit Union",
    "Aegis Banks",
    "Principle Financial Inc.",
    "Goldleaf Bank Corp.",
    "Prosperity Financial Group",
    "New National Holding Company",
    "Goldleaf Credit Union",
    "Edge Trust",
    "Apogee Bank Corp.",
    "Reliance Financial Services",
    "Fundament Financial Services",
    "Alpha Trust",
    "Bulwark Financial Inc.",
    "Omega Bancorp",
    "Caliber Banks Inc.",
    "Celestial Banks Inc.",
    "Midland Bank Group",
    "Groundwork Bank Group",
    "Global Network Bank Corp.",
    "Resolution Financial",
    "New Connection Financial Inc.",
    "Green Valley Bank",
    "Jones Bancorp",
    "Miracle Financial",
    "Apex Corporation",
    "Oculus Trust Corp.",
    "Oculus Financial Holdings",
    "Solace Trust",
    "Monolith Financial Group",
    "Monolith Corporation",
    "Grade Holdings Inc.",
    "Prosperity Financial Group",
    "Bolt Financial Corp.",
    "Wellspring Banks",
    "Premium Banks Inc.",
    "Citizen Union Trust Corp.",
    "State Bank Inc.",
    "Commonwealth Financial",
    "New Wave Bank",
    "Apex Bank Inc.",
    "Gold Credit Trust",
    "Armament Credit Union",
    "Armament Bancorp",
    "Bastion Banks Inc.",
    "Gold Alliance Trust Corp.",
    "Prosperity Banks Inc.",
    "Lifespark Bank",
    "Celestial Holdings Inc.",
    "Groundwork Corporation",
    "Prime Financial Corp.",
    "Crest Bank System",
    "Kindred Bank Inc.",
    "Principal Trust Corp.",
    "Diligence Bank System",
    "Clover Bank Inc.",
    "Victory Bancshares",
    "National Financial Holdings",
    "Boon Bank Group",
    "Boon Banks",
    "Prominence Banks Inc.",
    "One Nation Holdings Inc.",
    "New Heights Holdings Inc.",
    "Virtue Financial Inc.",
    "Monolith Corporation",
    "Zion Banks Inc.",
    "Caliber Bank System",
    "Sprout Bank",
    "Padlock Holdings",
    "Credence Banks",
    "Better Life Banks Inc.",
    "Apex Financial Holdings",
    "Fundament Corporation",
    "Caliber Bank Inc.",
};

const std::string possible_adress_street_RUS[] = {
    "Мирный путь",
    "Лоуленд Роу",
    "Авиационный проезд",
    "Садовый проезд",
    "Благословенный путь",
    "Полумесяц",
    "Грозовой ряд",
    "Северный маршрут",
    "Авеню орхидей",
    "Брумский проспект",
    "Виста Лейн",
    "Снежинка улица",
    "Музейный переулок",
    "Ореховый маршрут",
    "Лилипад Лейн",
    "Вейл Лейн",
    "Брумский проспект",
    "Маркетный переулок",
    "Путь справедливости",
    "Соловьиный путь",
    "Перьевой путь",
    "Вершинная улица",
    "Луна Роу",
    "Авеню Лотосов",
    "Сапфировый путь",
    "Тисовый ряд",
    "Мельничный проспект",
    "Якорный маршрут",
    "Музейный переулок",
    "Фермерская улица",
    "Солнечный переулок",
    "Тополиный путь",
    "Береговой ряд",
    "Широкий проезд",
    "Принц Пассаж",
    "Светлая улица",
    "Каверн Лейн",
    "Хайленд бульвар",
    "Медный проспект",
    "Пассажирская реликвия",
    "Королевская улица",
    "Редвуд Роу",
    "Солнечный бульвар",
    "Колокольный маршрут",
    "Аркадный маршрут",
    "Троицкий переулок",
    "Солнечный бульвар",
    "Виста Роу",
    "Снежный переулок",
    "Снежный бульвар",
    "Коммерческий переулок",
    "Арктический проход",
    "Сенна Пассаж",
    "Серебряная улица",
    "Лесной ряд",
    "Улица безмятежности",
    "Путь орхидей",
    "Дубовый переулок",
    "Полковничья улица",
    "Сердечный ряд",
    "Водный проезд",
    "Ривер Лейн",
    "Королевский бульвар",
    "Лесной бульвар",
    "Желудевый проспект",
    "Элмвуд-авеню",
    "Лунный путь",
    "Университетский маршрут",
    "Союз Пассаж",
    "Авеню Легенд",
    "Гротовый маршрут",
    "Лесной проезд",
    "Ягодный пассаж",
    "Тренерская улица",
    "Пенроуз-авеню",
    "Виста Лейн",
    "Лунный ряд",
    "Гранд Лейн",
    "Кросс-стрит",
    "Луна Роу",
    "Рован бульвар",
    "Полумесяц",
    "Новый переулок",
    "Колледж бульвар",
    "Мандаринский маршрут",
    "Центральный путь",
    "Авиационный переулок",
    "Океанский бульвар",
    "Нижний ряд",
    "Путь справедливости",
    "Дорога наследия",
    "Улица безмятежности",
    "Теневой путь",
    "Гранитная улица",
    "Гротовый маршрут",
    "Малый пассаж",
    "Монументальный бульвар",
    "Летний маршрут",
    "Зеленый пассаж",
    "Центральный переулок",
};

const std::string possible_adress_street[] = {
    "Peace Route",
    "Lowland Row",
    "Aviation Passage",
    "Orchard Passage",
    "Blessing Route",
    "Crescent Way",
    "Storm Row",
    "North Route",
    "Orchid Avenue",
    "Broom Avenue",
    "Vista Lane",
    "Snowflake Street",
    "Museum Lane",
    "Walnut Route",
    "Lilypad Lane",
    "Vale Lane",
    "Broom Avenue",
    "Market Lane",
    "Justice Route",
    "Nightingale Way",
    "Feathers Way",
    "Summit Street",
    "Luna Row",
    "Lotus Avenue",
    "Sapphire Way",
    "Yew Row",
    "Mill Avenue",
    "Anchor Route",
    "Museum Lane",
    "Farmer Street",
    "Sunshine Lane",
    "Poplar Way",
    "Beach Row",
    "Broad Passage",
    "Prince Passage",
    "Bright Street",
    "Cavern Lane",
    "Highland Boulevard",
    "Copper Avenue",
    "Heirloom Passage",
    "King Street",
    "Redwood Row",
    "Sunny Boulevard",
    "Bell Route",
    "Arcade Route",
    "Trinity Lane",
    "Sunny Boulevard",
    "Vista Row",
    "Snowflake Lane",
    "Snowflake Boulevard",
    "Commercial Lane",
    "Arctic Passage",
    "Senna Passage",
    "Silver Street",
    "Forest Row",
    "Serenity Street",
    "Orchid Way",
    "Oak Lane",
    "Colonel Street",
    "Heart Row",
    "Water Passage",
    "River Lane",
    "Kings Boulevard",
    "Timber Boulevard",
    "Acorn Avenue",
    "Elmwood Avenue",
    "Moon Way",
    "University Route",
    "Union Passage",
    "Legend Avenue",
    "Grotto Route",
    "Timber Passage",
    "Berry Passage",
    "Coach Street",
    "Penrose Avenue",
    "Vista Lane",
    "Moonlight Row",
    "Grand Lane",
    "Cross Street",
    "Luna Row",
    "Rowan Boulevard",
    "Crescent Way",
    "Nova Lane",
    "College Boulevard",
    "Mandarin Route",
    "Centre Way",
    "Aviation Lane",
    "Ocean Boulevard",
    "Lower Row",
    "Justice Route",
    "Heritage Route",
    "Serenity Lane",
    "Shadow Route",
    "Granite Street",
    "Grotto Route",
    "Little Passage",
    "Monument Boulevard",
    "Summer Route",
    "Green Passage",
    "Centre Lane",
};
